accounts/urls.py
from django.urls import path                                                                                                                                                                                                                                                                                                                                
from . import views
# from django.contrib.auth.decorators import user_passes_test
# from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PwordResetForm, PwordResetConfirmForm, PwordChangeForm
from .views import ProfileUpdateView, ProfileView
app_name = 'accounts'


urlpatterns = [
    path('register/', views.register, name='register'),
    # Profile
    # path('profile/', ProfileView.as_view(), name='profile'),
    # path('profile/edit/', ProfileUpdateView.as_view(), name='edit'),
    # path('edit/', views.edit_profile, name='edit'),
    path('profile/edit/', views.edit, name='edit'),

     path('profile/', views.profile, name='profile'),
    # path('profile/edit/', views.edit_profile, name='edit'),
    # path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                             authentication_form=UserLoginForm), name='login'),
    path('login/', views.login, name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="registration/password_change_form.html", form_class=PwordChangeForm), name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password_reset_form.html", form_class=PwordResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwordResetConfirmForm), name="pwdresetconfirm"),
    # #path('/logout', auth_views.logout_then_login, name='logout'),
    # path('logout/', views.logout, name="logout"),
    # path('login/', views.login, name="login"),

    path('activate/<slug:uidb64>/<slug:token>)/', views.activate, name='activate'),

    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/users', views.users, name='users'),
    path('admin-dashboard/users/<int:id>', views.user_page, name='user_page'),
    path('admin-dashboard/user/<int:id>', views.delete_user, name='delete_user'),
    path('admin-dashboard/questions/', views.questionsPage, name='questions'),
    path('admin-dashboard/answers/', views.answersPage, name='answers'),
    path('admin-dashboard/questions/<int:pk>', views.delete_question, name='delete_question'),
    path('admin-dashboard/groups/', views.groups, name='groups'),
    path('admin-dashboard/groups/<int:id>', views.group_page, name='group_page'),
    path('admin-dashboard/groups/<int:id>', views.group_add_user, name='group_add_user'),

    path('admin-dashboard/topics/',views.topics,name='topics'),
    path('admin-dashboard/topic/<int:pk>',views.topic,name='topic'),
    # path('admin-dashboard/topic/delete-topic/<int:pk>', views.deleteTopic, name='delete_topic'),
    path('admin-dashboard/question/<int:id>', views.single_question_page, name='single_question_page'),







]

main/urls.py
from django.urls import path
from . import views
from .views import UpdateQuestionView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns






app_name = 'main'


urlpatterns = [
    path('', views.home, name='home'),
    path('questions/', views.questionsPage, name='questions_page'),
    path('ask-question/', views.ask_question, name='ask_question'),
    path('question/<int:id>', views.single_question_page, name='single_question_page'),
    path('update-question/<int:id>', views.updateQuestion, name="update_question"),
    path('delete-question/<int:pk>', views.deleteQuestion, name="delete_question"),
    path('fav/<int:id>', views.favourite_add, name='favourite_add'),
    path('profile/favourites/', views.favourite_list, name='favourite_list'),
    path('delete-answer/<int:pk>', views.deleteAnswer, name="delete_answer"),
    path('update-answer/<int:pk>', views.updateAnswer, name="update_answer"),
    path('topic/<int:pk>',views.topic,name='topic'),

   # Tag Page
    path('tag/<str:tag>',views.tag,name='tag'),
    # Tags Page
    path('tags',views.tags,name='tags'),

    path('search/', views.question_search, name='question-search'),

    path('topic/<int:pk>/followers/add', views.followTopic, name='follow-topic'),

    path('topic/<int:pk>/followers/remove', views.unfollowTopic, name='unfollow-topic'),

    path('answer/<int:pk>/like', views.AddLike, name='like'),
    path('answer/<int:pk>/dislike', views.AddDislike, name='dislike'),

    path('topics/',views.topics,name='topics'),

    path('add-topic/', views.add_topic, name='add_topic'),

    





]


#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ohc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings
admin.site.site_title = "OHC"
admin.site.site_header = "OHC"
admin.site.index_title = "OHC"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),

    
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

main/models.py
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


# Topic
class Topic(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100,)
    follow = models.ManyToManyField(CustomUser, blank=True, related_name='follow')


    def __str__(self):
        return self.topic

    
# Question Model
class Question(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    topic = models.ForeignKey("Topic", null=True, blank=True, on_delete=models.DO_NOTHING)
    body = models.TextField()
    tags = models.TextField(default='')
    favourites = models.ManyToManyField(
        CustomUser, related_name='favourite', default=None, blank=True)
    add_time = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manage
    def __str__(self):
        return self.title

# Answer Model
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(CustomUser, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(CustomUser, blank=True, related_name='dislikes')

    def __str__(self):
        return self.answer

templates/ask-question.html
{% extends 'base.html' %}
{% block title %}Ask Question | OHC{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="card mt-5 mb-5 col-md-6">
            <h5 class="card-header">Ask Question</h5>
            <div class="card-body">
                <!-- {% for message in messages %}
                <div class="alert alert-success" role="alert">
                {{message}}
                </div>
                {% endfor %} -->
                <form method="post"action="{% url 'main:ask_question' %}">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/create-post.html
{% extends 'base.html' %}
{% block title %}OHC | Share Your Story{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="card mt-5 mb-5 col-md-6">
            <h5 class="card-header">Share Your Story</h5>
            <div class="card-body">
                {% for message in messages %}
                <div class="alert alert-success" role="alert">
                {{message}}
                </div>
                {% endfor %}
                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
 

templates/favourites.html
{% extends 'base.html' %}
{% block title %}Ask Question | OHC{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-3 mb-3">
    <div>
        <div class="row">
            {% if new %}
            {% for post in new %}
            <div class="col-md-4">
                <div class="text-dark">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h4><a style="font-size:22px;font-weight:bold" href="{% url 'main:single_question_page' post.id%}">{{post.title}}</a><h4>
                            <p class="card-text">{{post.body|truncatechars:40}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{post.add_time}}</small>
                                <div id="favourite-section"><a href="{% url 'main:favourite_add' post.id %}"
                                        class="btn btn-outline-primary">Remove</a></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-8">
                    <div class=" mb-4 box-shadow">
                    <h4>You have not saved any questions</h4>    
                    </div>
            </div>            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<footer class="footer footer text-center mt-auto py-3 bg-light">
    <div class="container">
        <p class="mb-1">&copy; 2021 OHC</p>
    </div>
  </footer>

  

templates/home.html
{% extends 'base.html' %}
{% block title %}OHC | Home{% endblock %}
{% block content %}
    <!-- Search Section -->
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
            </div>
        </div>             
    </div>
    <!-- Question List -->
 
    
    <div class="container mb-2">
        {% if user.is_authenticated %}
        {% for question in questions %}
            <div class="row d-flex justify-content-center">
                <div class="card mt-4 col-md-8">
            <div class="card-body">
                <h4 class="card-title"><a href="/question/{{question.id}}">{{question.title}}</a></h4>
                <p class="card-text">{{question.body}}</p>
                <p>
                    <!-- <a href="#" class="mr-2">{{question.answer_set.count}} Answers</a> -->
                </p>
            </div>
            <div class="card-footer">
                <small href="#" class="mr-2"><span class="badge badge-info">{{question.answer_set.count}}</span> {% if question.answer_set.count == 1%}Answer {% else %} Answers {% endif %}</small>
                <small>{{question.add_time}}</small>
                <small class="mr-2 ml-2">{{question.user.username}}</small>
            </div>
        </div>
        </div>
        
        {% endfor %}
        {% else %}

        {% for question in questions %}
            <div class="row d-flex justify-content-center">
                <div class="card mt-2 col-md-8">
            <div class="card-body">
                <h4 class="card-title"><a href="/question/{{question.id}}">{{question.title}}</a></h4>
                <p class="card-text">{{question.body|truncatewords:10}}</p>
                <p>
                    <!-- <a href="#" class="mr-2">{{question.answer_set.count}} Answers</a> -->
                </p>
            </div>
            <div class="card-footer">
                <small href="#" class="mr-2"><span class="badge badge-info">{{question.answer_set.count}}</span> {% if question.answer_set.count == 1%}Answer {% else %} Answers {% endif %}</small>
                <small>{{question.add_time}}</small>
                <small>{{question.user.username}}</small>
            </div>
        </div>
        </div>
        
        {% endfor %}

        {% endif %}
    </div>
    {% if questions.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if questions.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{questions.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in questions.paginator.page_range %}
          {% if questions.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if questions.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{questions.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}

templates/navigation.html
{% load user_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
      <a class="navbar-brand" href="/">OHC</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <form class="ml-auto" method="GET" action="{% url 'main:question-search' %}">
            <div class="input-group col-auto col-sm-12 col-md-12">
              <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
              <div class="input-group-append">
                <button class="btn btn-outline-primary btn-lg" type="submit" id="button-addon2">Search</button>
              </div>
            </div>
          </form>
            <ul class="navbar-nav ml-auto">
              {% if request.user|has_group:"moderators" or request.user|has_group:"admins" %}

              <li class="nav-item active">
                <a class="nav-link btn btn-primary" href="{% url 'admin:index' %}">Go to Dashboard</a>
              </li>
              {% endif %}
              <li class="nav-item active">
                  <a class="nav-link" href="/">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="/ask-question">Ask Question</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="/questions">Questions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/topics">Topics</a>
          </li>
              <li class="nav-item">
                <a class="nav-link" href="/tags">Tags</a>
            </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
              <!-- <a class="nav-link" href="{% url 'main:favourite_list' %}">Saved Posts</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/account/profile/{{user.id}}">Profile</a>
              </li>            -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle pl-1 pr-0" href="#" id="navbarDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">Dashboard</a>
                    <!-- <a class="dropdown-item" href="{% url 'accounts:edit' %}">Edit details</a> -->
                    <a class="dropdown-item" href="{% url 'main:favourite_list' %}">Saved Questions</a>
                    <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            <!-- </li>              <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li> -->
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="/account/login">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/account/register">Register</a>
              </li>
              {% endif %}
          </ul>
</div>
  </div>
</nav>

templates/posts-page.html
{% extends 'base.html' %}
{% block title %}OHC | Home{% endblock %}
{% block content %}
    <!-- Search Section -->
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-floating">
                    <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                    <label for="floatingTextarea2">Comments</label>
                  </div>
            </div>
        </div>             
    </div>
    <!-- Question List -->
 
    
    <div class="container">
        {% for post in posts %}
            <div class="row d-flex justify-content-center">
                <div class="card mt-4 col-md-8">
            <div class="card-body">
                <h4 class="card-title"><a href="/post/{{post.id}}">{{post.title}}</a></h4>
                <p class="card-text">{{post.body|truncatewords:100}}</p>
                <p>
                    <a href="#" class="mr-2">{{post.user.username}}</a>
                    <!-- <a href="#" class="mr-2">{{question.answer_set.count}} Answers</a> -->
                    <a href="#" class="mr-2">{{post.total_comments}} Comments</a>
                </p>
            </div>
            <div class="card-footer">
                <small>{{post.add_time}}</small>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    {% if posts.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if posts.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{posts.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if posts.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{posts.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}

templates/single-question.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}OHC | {{question.title}}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% load mathfilters %}
<!-- Single question starts here -->
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="card mt-1 mb-1 col-md-9 col-sm-8">
          <div class="row">
            <div class="col-md-10 col-sm-4 my-3"> 
            <h2>{{question.title}}</h2>
            </div>
            <div class="col-md-2 my-3"> 
              {% if fav %}
              <div>
                <a href="{% url 'main:favourite_add' question.id %}" class="btn btn-sm btn-outline-danger">Remove from bookmark</a>
              </div>
              {% else %}
              <div>
                <a href="{% url 'main:favourite_add' question.id %}" class="btn btn-sm btn-outline-primary">Add to bookmark</a>
              </div>
              {% endif %}
            </div>
          </div>
        <p>{{question.body}}</p>
        <p>
            tags:
            {% for tag in tags %}
            <a href="/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
            {% endfor %}
        </p>
        <p>
          <a href="#">{{question.user.username}}</a>
<span>{{question.answer.count}}</span>
            {% if question.user.id == request.user.id %}
            <a class="btn btn-sm btn-primary mr-2" href="{% url 'main:update_question' question.id %}">Edit</a>
            <a class="btn btn-sm btn-danger mr-2" data-toggle="modal" data-target="#exampleModalQuestion">Delete</a>
            {% endif %}
            <!-- <a  href="/topic/{{topic.id}}" class="btn btn-secondary btn-sm">{{question.topic}}</a> -->
            

            <span class="mr-4">{{question.add_time|date:'d/m/Y'}}</span>
        </p>



        <!-- Confirm deletion modal -->
        <div class="modal fade" id="exampleModalQuestion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete "{{question.title}}"?</p>
                <form method="POST" action="{% url 'main:delete_question' question.id %}" class="mt-3 mb-3">
                  {% csrf_token %}
                <a class="btn btn-secondary" href="{% url 'main:single_question_page' question.id %}">Cancel</a>
                <input class="btn btn-danger" value="Delete" type="submit" name="Confirm">
              </form>
              </div>
            </div>
          </div>
        </div>
        <hr/>
        {% if user.is_authenticated %}
        <form method="post" >
            {% csrf_token %}
            {{answerForm|crispy}}
            <button type="submit" class="btn btn-primary">Post Answer</button>      
        </form>
        <hr/>
        {% endif %}
    <!-- Answers start here -->
    {% for answer in answers %}
    <div class="row">
      <div class="col-1 col-sm-2" style="text-align: center;">
        <div class="upvote">
{% comment %}<strong class="upvote-count-{{answer.id}}"> <span>{{ answer.likes.all.count }}</span></strong>{% endcomment %}<br/>
          <form method="POST" action="{% url 'main:like' answer.pk %}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button class="text-success" type="submit">
                  <i class="fa fa-arrow-up fa-2x upvote-click"></i>
              </button>
          </form>
        </div>
        <strong><span>{{answer.likes.all.count |sub:answer.dislikes.all.count}}</span></strong>
        <div class="downvote">
          <form method="POST" action="{% url 'main:dislike' answer.pk %}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button class="text-danger" type="submit">
                  <i class="fa fa-arrow-down fa-2x downvote-click"> </i>
              </button>
          </form>
          {% comment %}<strong class="downvote-count-{{answer.id}}"><span>{% if answer.dislikes.all.count != 0 %}-{% endif %}{{ answer.dislikes.all.count }}</span></strong>{% endcomment %}

      </div>
      </div>
    <div class="col-10 align-items-end">

      <div class="card">

        <div class="card-body">
       <p>{{answer.answer}}</p>
        </div>
        <div class="card-footer text-muted">
          <a href="#" class="mr-1">{{answer.user.username}}</a>
            {% if answer.user.id == request.user.id %}
            <a class="btn btn-sm btn-primary mr-2" href="{% url 'main:update_answer' answer.id %}">Edit</a>
            <a class="btn btn-sm btn-danger mr-2" href="{% url 'main:delete_answer' answer.id %}">Delete</a>
            {% elif answer.question.user.id == request.user.id %}
            <a class="btn btn-sm btn-danger mr-2" data-toggle="modal" data-target="#deleteanswerModal">Delete</a>
            {% endif %}
            <span>{{answer.add_time|date:'d/m/Y h:i:s'}}</span>
                 
        </div>
      </div>

<!-- Modal -->
<div class="modal fade" id="deleteanswerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete "{{answer}}"?</p>
        <form method="POST" action="{% url 'main:delete_answer' answer.id %}" class="mt-3 mb-3">
          {% csrf_token %}
         <a class="btn btn-secondary" href="{% url 'main:single_question_page' question.id %}">Cancel</a>
         <input class="btn btn-danger" value="Delete" type="submit" name="Confirm">
       </form>
      </div>
    </div>
  </div>
</div>

<!-- Edit answer modal -->

<div class="modal fade" id="EditAnswerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Answer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{% url 'main:update_answer' answer.id %}" class="mt-3 mb-3">
          {% csrf_token %}
          {{answerForm.answer}}
        <a class="btn btn-secondary" href="{% url 'main:single_question_page' question.id %}">Cancel</a>
        <input class="btn btn-primary" value="Save Changes" type="submit" name="Confirm">
      </form>
      
      </div>
    </div>
  </div>
</div>


    </div>
</div>
<hr/>
{% endfor %}


    </div>
        


    </div>
</div>



{% endblock %}

templates/topics.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}
{% block title %}All Tags{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<!-- add topics -->
{% if request.user|has_group:"moderators" %}
<div class="container col-md-6">
    <div class="row">

      <a class="btn btn-primary  mr-2 ml-2 mt-2 mb-2" data-toggle="modal" data-target="#AddTopicModal">Add a topic</a>
    </div>
    <div class="modal fade" id="AddTopicModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="Add Topic Modal">Add a new topic</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form method="POST" action="{% url 'main:add_topic' %}" class="mt-3 mb-3">
                {% csrf_token %}
                {{topicForm|crispy}}
              <a class="btn btn-secondary" href="{% url 'main:topics' %}">Cancel</a>
              <input class="btn btn-primary" value="Save Changes" type="submit" name="Confirm">
            </form>
            
            </div>
          </div>
        </div>
      </div>
</div>
{% endif %}

<!-- topics -->                 

<div class="container col-md-6 mb-4 mt-4">
  {% for topic in topics %}
  <div class="d-flex text-muted pt-3">

    <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
      <div class="d-flex justify-content-between">
        <h5 class="text-gray-dark col-md-6"><a href="{% url 'main:topic' topic.id %}">{{topic.topic}}</a> <span class="badge badge-primary">{{topic.follow.count}}</span></h5>
      </div>
    </div>
  </div>
 
  {% endfor %}
  </div>

{% endblock %}

templates/update-answer.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}OHC | {{answer.answer}}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<br>
<div class="container">
<div class="row d-flex justify-content-center">
	<div class="col-md-6">
		<div class="card card-body mb-3">
			
			<h4>Update Answer</h4>
			<form method="POST" action="{% url 'main:update_answer' answer.id %}">
				 {% csrf_token %}
				 {{form|crispy}}
				<a class="btn btn-warning" href="{% url 'main:single_question_page' answer.question.id %}">Cancel</a>
				<input class="btn btn-primary" type="submit" value="Update answer" name="Confirm">
			</form>
		</div>
	</div>
</div>
</div>

{% endblock %}